name: ogden-eu
channels:
  - default
dependencies:
  - python=3.7
  - numpy=1.14
  - scipy=1.1
  - matplotlib=3.2
  - seaborn=0.10
  - cython=0.28
  - qutip=4.3
  - pip
  - pip:
    - maxwellbloch==0.7.0
